# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/https://github.com/arun477/miniai.git',
                'doc_host': 'https://arun477.github.io',
                'git_url': 'https://github.com/arun477/https://github.com/arun477/miniai.git',
                'lib_path': 'https://github.com/arun477/miniai.git'},
  'syms': {'miniai.git.core': {'miniai.git.core.foo': ('core.html#foo', 'miniai.git/core.py')}}}
