# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/miniai',
                'doc_host': 'https://arun477.github.io',
                'git_url': 'https://github.com/arun477/miniai',
                'lib_path': 'miniai'},
  'syms': { 'miniai.core': {'miniai.core.foo': ('core.html#foo', 'miniai/core.py')},
            'miniai.lec_10_v4': {},
            'miniai.lec_9_v4': {},
            'miniai.lec_9_v5': {}}}
