# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/miniai',
                'doc_host': 'https://arun477.github.io',
                'git_url': 'https://github.com/arun477/miniai',
                'lib_path': 'miniai'},
  'syms': { 'miniai.core': {'miniai.core.foo': ('core.html#foo', 'miniai/core.py')},
            'miniai.datasets': {},
            'miniai.training': { 'miniai.training.Dataset': ('training.html#dataset', 'miniai/training.py'),
                                 'miniai.training.Dataset.__getitem__': ('training.html#dataset.__getitem__', 'miniai/training.py'),
                                 'miniai.training.Dataset.__init__': ('training.html#dataset.__init__', 'miniai/training.py'),
                                 'miniai.training.Dataset.__len__': ('training.html#dataset.__len__', 'miniai/training.py'),
                                 'miniai.training.accuracy': ('training.html#accuracy', 'miniai/training.py'),
                                 'miniai.training.fit': ('training.html#fit', 'miniai/training.py'),
                                 'miniai.training.get_dls': ('training.html#get_dls', 'miniai/training.py'),
                                 'miniai.training.report': ('training.html#report', 'miniai/training.py')}}}
